version: '3.8'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: laravel_app

    restart: unless-stopped

    working_dir: /var/www

    volumes:
      - public_data:/var/www/public
      #  - .:/var/www

    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_KEY: ${APP_KEY}

      LOG_CHANNEL: stack

      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: secret

      CACHE_DRIVER: file
      SESSION_DRIVER: file
      QUEUE_CONNECTION: sync

      MONGODB_URI: mongodb://mongodb:27017/laravel

    depends_on:
      - postgres
      - mongodb

    networks:
      - app-network

  nginx:
    image: nginx:alpine

    container_name: nginx

    restart: unless-stopped

    ports:
      - "80:80"

    volumes:
      - public_data:/var/www/public 
      # - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - app

    networks:
      - app-network

  postgres:
    image: postgres:16-alpine

    container_name: postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret

    volumes:
      - postgres_data:/var/lib/postgresql/data

    ports:
      - "5432:5432"

    networks:
      - app-network

  mongodb:
    image: mongo:7

    container_name: mongodb

    restart: unless-stopped

    volumes:
      - mongodb_data:/data/db

    ports:
      - "27017:27017"

    networks:
      - app-network

volumes:
  public_data:
  postgres_data:
  mongodb_data:

networks:
  app-network:
    driver: bridge